name: Exercice 3 

on: 
  push:
    branches: 
      - main      # push sur main
  pull_request:
    branches:
      - main

jobs: 
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: 1) Récupèration du code
        uses: actions/checkout@v4
 
      - name: 2) Installer NodeJS
        uses: actions/setup-node@v4

      - name: 3) Installer les dépendances
        run: npm i

      - name: 4) Exécution de Lint
        run: npm run lint:check

      - name: 5) audit 
        run: npm audit
        
      - name: 5) Créer zip de chrome et firefox
        run: npm run zip && npm run pack:zip