name: Exercice 3 

on: 
  push:
    branches: 
      - main      # push sur main
  pull_request:   # pull request sur branches main
    branches:
      - main


    runs-on: ubuntu-latest
    step:
      - name: 1) Récupèration du code
        uses: actions/checkout@v4
  
      - name: 2) Installer NodeJS
        uses: actions/setup-node@v4

      - name: 3) Installer les dépendances
        run: npm i

      - name: 4) Exécution de Lint
        run: npm run lint:check

      - name: 5) audit 
        run: npm audit fix
        
      - name: 5) Créer zip de chrome et firefox
        run: npm run zip

      - name: 5) Uplaod l'artefact
        uses: action/upload-artifact@v4
        with:
          name: artefact
          path: ./

